version: '3'

services:
  backend:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm run serve"
    ports:
      - "8083:8080"