version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  mongo_data: